name: win-msbuild-actions-workflow
on: push
jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64
          
      - name: Build app for release
        run: MSBuild.exe Lab8_Complete_2022.sln /p:Configuration=Release /p:Platform="x64"
